# frozen_string_literal: true

require 'minitest/autorun'
require 'tmpdir'
require 'fileutils'
require 'open3'

class TestIndexGeneration < Minitest::Test
  BIN = File.expand_path('../leeni', __dir__)

  INDEX_DOC_TEX = <<~LATEX
    \\documentclass{article}
    \\usepackage{makeidx}
    \\makeindex
    \\begin{document}
    Testing index generation with latex\\_it\\index{sample}.
    \\printindex
    \\end{document}
  LATEX

  def setup
    skip 'makeindex not installed' unless system('which makeindex >/dev/null 2>&1')
  end

  def test_index_generation_with_flag
    Dir.mktmpdir('leeni_index_test') do |dir|
      doc_path = File.join(dir, 'paper.tex')
      File.write(doc_path, INDEX_DOC_TEX)

      out, stderr, status = Open3.capture3(BIN, '-I', 'paper.tex', chdir: dir)
      assert status.success?, "Build failed: #{stderr}\nOutput: #{out}"

      assert File.file?(File.join(dir, 'paper.pdf')), 'Target PDF not generated'
      assert File.file?(File.join(dir, 'junk', 'paper.idx')), 'junk/paper.idx not generated'
      assert File.file?(File.join(dir, 'junk', 'paper.ind')), 'junk/paper.ind not generated by makeindex'
      assert_includes out, 'makeindex'

      ind_content = File.read(File.join(dir, 'junk', 'paper.ind'))
      assert_includes ind_content, 'sample'

      # Second run should be up-to-date
      out2, _, status2 = Open3.capture3(BIN, '-I', 'paper.tex', chdir: dir)
      assert status2.success?
      assert_includes out2, 'up-to-date'
    end
  end

  def test_index_skipped_by_default
    Dir.mktmpdir('leeni_no_index_test') do |dir|
      doc_path = File.join(dir, 'paper.tex')
      File.write(doc_path, INDEX_DOC_TEX)

      out, stderr, status = Open3.capture3(BIN, 'paper.tex', chdir: dir)
      assert status.success?, "Build failed: #{stderr}\nOutput: #{out}"

      assert File.file?(File.join(dir, 'paper.pdf'))
      refute File.file?(File.join(dir, 'junk', 'paper.ind')), 'makeindex should not run without -I'
      refute_includes out, 'makeindex'
    end
  end

  def test_index_enabled_via_local_config
    Dir.mktmpdir('leeni_config_index_test') do |dir|
      # Persist index choice first
      out_save, _, status_save = Open3.capture3(BIN, '-I', '--config-save', chdir: dir)
      assert status_save.success?
      assert_includes out_save, 'Saved index to local configuration'

      # Now create paper.tex
      doc_path = File.join(dir, 'paper.tex')
      File.write(doc_path, INDEX_DOC_TEX)

      # Build without -I flag on command line
      out, stderr, status = Open3.capture3(BIN, 'paper.tex', chdir: dir)
      assert status.success?, "Build failed: #{stderr}\nOutput: #{out}"

      assert File.file?(File.join(dir, 'junk', 'paper.ind')), 'junk/paper.ind should be generated via config'
      assert_includes out, 'makeindex'
    end
  end

  def test_index_rebuild_on_updated_entry
    Dir.mktmpdir('leeni_index_update') do |dir|
      doc_path = File.join(dir, 'paper.tex')
      File.write(doc_path, INDEX_DOC_TEX)

      Open3.capture3(BIN, '-I', 'paper.tex', chdir: dir)

      # Update document with a new index entry
      updated_tex = INDEX_DOC_TEX.sub('\\index{sample}', "\\index{sample}\nAnother\\index{zebra}")
      sleep 1 # Ensure mtime advancement
      File.write(doc_path, updated_tex)

      out, stderr, status = Open3.capture3(BIN, '-I', 'paper.tex', chdir: dir)
      assert status.success?, "Rebuild failed: #{stderr}\nOutput: #{out}"
      assert_includes out, 'makeindex'

      ind_content = File.read(File.join(dir, 'junk', 'paper.ind'))
      assert_includes ind_content, 'zebra'
    end
  end
end
