# frozen_string_literal: true

# ==============================================================================
# lib/leeni/help_manual.rb
#
# Comprehensive man-page style manual generator for leeni (-H, --help-all).
# Detailed explanations and practical usage examples for every CLI option.
# ==============================================================================

module LaTeXHelpManual
  def self.render(prog_name = 'l')
    sections = [
      banner_section(prog_name),
      compilation_options_section,
      cleaning_options_section,
      diagnostics_options_section,
      packaging_options_section,
      arxiv_options_section,
      environment_options_section,
      general_options_section
    ]
    sections.join("\n\n")
  end

  def self.banner_section(_prog_name = 'l')
    [
      'Usage: l [options] [document.tex]',
      '',
      'leeni compiles LaTeX documents incrementally using XeLaTeX, LuaLaTeX,',
      'or pdfLaTeX. It isolates auxiliary build files into junk/, manages convergence',
      'rerun loops, filters engine logs into clean tiered diagnostics, and provides',
      'paper packaging, arXiv submission preparation, and editor integration.'
    ].join("\n")
  end

  def self.compilation_options_section
    [
      'Compilation Options:',
      '',
      '  Pass Control & Compilation:',
      '  -f, --force',
      '      Force compilation run unconditionally, bypassing the build cache',
      '      and ignoring up-to-date checks in junk/.build_state.json.',
      '      Example:',
      '        l -f',
      '        l -f paper.tex',
      '',
      '  -u, --single-pass',
      '      Execute a single LaTeX pass only (fast draft mode). Bypasses the build',
      '      cache, disables BibTeX/Biber resolution, and skips rerun loops.',
      '      Example:',
      '        l -u',
      '        l -u paper.tex',
      '',
      '  -n, --passes NUM',
      '      Maximum number of compilation passes allowed (default: 5) during the',
      '      convergence loop when resolving cross-references and bibliography updates.',
      '      Example:',
      '        l -n 2 paper.tex',
      '',
      '  -b, --[no-]bib',
      '      Explicitly enable or skip bibliography resolution pass (BibTeX or Biber).',
      '      By default, leeni automatically detects whether a pass is required.',
      '      Example:',
      '        l --no-bib paper.tex',
      '        l -b paper.tex',
      '',
      '  -I, --[no-]index',
      '      Run makeindex pass when document index source (.idx) changes or index output',
      '      (.ind) is missing. Automatically reruns LaTeX until convergence.',
      '      Disabled by default.',
      '      Example:',
      '        l -I paper.tex',
      '        l --no-index paper.tex',
      '',
      '  -e, --engine ENGINE',
      '      Select TeX compiler engine: x (xelatex, default), l (lualatex), or p (pdflatex).',
      '      Can also be set via magic comment "% !TEX program = ..." in the main .tex file.',
      '      Example:',
      '        l -e l paper.tex',
      '        l --engine=pdflatex paper.tex',
      '',
      '  --timeout SECONDS',
      '      Maximum execution timeout in seconds allowed per external subprocess pass.',
      '      Prevents hung builds on infinite TeX macro loops.',
      '      Example:',
      '        l --timeout 30 paper.tex',
      '',
      '  -T, --time',
      '      Display execution wall-clock time breakdown per compilation and bibliography pass.',
      '      Example:',
      '        l -T paper.tex'
    ].join("\n")
  end

  def self.cleaning_options_section
    [
      'Cleaning & Output Management:',
      '  -c, --clean',
      '      Remove temporary build artifacts in junk/ and regenerable root files before',
      '      initiating the compilation build.',
      '      Example:',
      '        l -c paper.tex',
      '',
      '  -C, --clean-only',
      '      Clean auxiliary files in the target directory and exit immediately without compiling.',
      '      Example:',
      '        l -C',
      '        l -C path/to/project/',
      '',
      '  --junk-dir DIR',
      '      Specify directory for temporary build artifacts (default: junk or .junk).',
      '      Can also be configured in .l.jsonc via "junk_dir": ".junk".',
      '      Example:',
      '        l --junk-dir .junk',
      '',
      '  --update-if-changed',
      '      Only replace target PDF if extracted text content changed, preventing external',
      '      PDF viewers from reloading on visually identical rebuilds.',
      '      Example:',
      '        l --update-if-changed paper.tex'
    ].join("\n")
  end

  def self.diagnostics_options_section
    [
      'Diagnostics & Error Filtering:',
      '  -r, --raw',
      '      Print raw, unfiltered compiler stdout and stderr directly during compilation passes.',
      '      Useful as a low-level debug pass-through tool. Bypasses the build cache.',
      '      Example:',
      '        l -r',
      '        l -r paper.tex',
      '',
      '  -x, --explain',
      '      Display boxed plain-English explanations and suggested fixes on first occurrence',
      '      of known LaTeX errors or warnings.',
      '      Example:',
      '        l -x paper.tex',
      '',
      '  -a, --all',
      '      Display all diagnostics across all severity tiers, including Whatevers and minor',
      '      warnings that are normally suppressed.',
      '      Example:',
      '        l -a paper.tex',
      '',
      '  -W, --werror',
      '      Treat compilation warnings as fatal errors; exits with status 1 if any warning occurs.',
      '      Example:',
      '        l -W paper.tex',
      '',
      '  -s, --score',
      '      Quiet score mode: suppresses regular stdout and prints only a compact numeric summary:',
      '      "<errors> <alerts> <warnings> [<pages>] [<seconds>]". Exits 0 on success.',
      '      Example:',
      '        l -s paper.tex',
      '',
      '  -v, --verbose',
      '      Verbose output mode: shows full log context snippets for overfull hbox and',
      '      auxiliary diagnostics.',
      '      Example:',
      '        l -v paper.tex',
      '',
      '  --trace',
      '      Print exact external subprocess commands, working directories, and environment overrides.',
      '      Example:',
      '        l --trace paper.tex',
      '',
      '  --alert-hbox PT',
      '      Overfull \\hbox threshold in points to promote a warning to an Alert (default: 24.0 pt).',
      '      Example:',
      '        l --alert-hbox 15.0 paper.tex',
      '',
      '  --whatever-pt PT',
      '      Overfull \\hbox threshold in points to demote a warning to a Whatever (default: 2.5 pt).',
      '      Example:',
      '        l --whatever-pt 1.0 paper.tex'
    ].join("\n")
  end

  def self.packaging_options_section
    [
      'Paper Packaging & Portability:',
      '  -z, --zip',
      '      Create a self-contained portable zip archive of the paper, bundling referenced',
      '      figures and local styles. Extra files can be appended after "--".',
      '      Example:',
      '        l -z paper.tex',
      '        l -z -- extra_fig.pdf appendix_data.csv',
      '',
      '  -Z, --zip-flat',
      '      Create a self-contained portable zip archive with all \\input and \\include files',
      '      recursively inlined into a single flattened .tex document.',
      '      Example:',
      '        l -Z paper.tex',
      '',
      '  -t, --verify',
      '      Verify self-contained portability by testing compilation of the packaged zip',
      '      in an isolated /tmp sandbox.',
      '      Example:',
      '        l -z -t paper.tex',
      '',
      '  --zip-name NAME',
      '      Specify custom output filename for generated zip archive.',
      '      Example:',
      '        l -z --zip-name manuscript.zip paper.tex',
      '',
      '  -B, --bib-extract [NAME]',
      '      Extract cited bibliography entries from global bibliographies into local .bib file',
      '      (default: <doc>.bib).',
      '      Example:',
      '        l -B paper.tex',
      '        l -B local_refs.bib paper.tex',
      '',
      '  --bib-name NAME',
      '      Specify custom output filename for extracted bibliography entries.',
      '      Example:',
      '        l -B --bib-name local_refs.bib paper.tex',
      '',
      '  --[no-]styles-inject',
      '      Enable or disable isolating harvested styles into styles/ and injecting \\input@path.',
      '      Example:',
      '        l -z --styles-inject paper.tex'
    ].join("\n")
  end

  def self.arxiv_options_section
    [
      'arXiv Preparation Options:',
      '  --arxiv',
      '      Prepare a sanitized, flattened, submission-ready arXiv zip package.',
      '      Example:',
      '        l --arxiv paper.tex',
      '',
      '  --arxiv-name NAME',
      '      Specify custom output filename for the generated arXiv package.',
      '      Example:',
      '        l --arxiv --arxiv-name arxiv_submission.zip paper.tex',
      '',
      '  --meta',
      '      Extract and display sanitized paper metadata (title, authors, abstract) and',
      '      write arxiv_<file>_meta.txt for copy-pasting into the arXiv submission form.',
      '      Example:',
      '        l --meta paper.tex',
      '',
      '  --[no-]arxiv-verify',
      '      Enable or disable sandbox compile plus exact PDF text verification (default: true).',
      '      Example:',
      '        l --arxiv --no-arxiv-verify paper.tex',
      '',
      '  --[no-]arxiv-visual-verify',
      '      Enable or disable rendered PDF page visual verification (default: true; requires pdftoppm).',
      '      Example:',
      '        l --arxiv --no-arxiv-visual-verify paper.tex',
      '',
      '  --[no-]biblatex-shield',
      '      Enable or disable bundling local biblatex distribution files to prevent skew (default: true).',
      '      Example:',
      '        l --arxiv --no-biblatex-shield paper.tex'
    ].join("\n")
  end

  def self.environment_options_section
    [
      'Environment, Theming & Configuration:',
      '  --[no-]color',
      '      Enable or disable colored terminal output (default: auto-detects TTY and NO_COLOR).',
      '      Example:',
      '        l --color paper.tex',
      '        l --no-color paper.tex',
      '',
      '  --[no-]link',
      '      Enable or disable clickable terminal hyperlinks (OSC 8) to source file/line locations.',
      '      Example:',
      '        l --link paper.tex',
      '        l --no-link paper.tex',
      '',
      '  --theme THEME',
      '      Set diagnostic color theme (blush, catppuccin, tokyo-night, dracula, nord, ansi,',
      '      or "+1" / "-1" to cycle through available themes).',
      '      Example:',
      '        l --theme catppuccin paper.tex',
      '        l --theme +1',
      '',
      '  --theme-list',
      '      List available diagnostic color themes with terminal previews and exit.',
      '      Example:',
      '        l --theme-list',
      '',
      '  --[no-]lock',
      '      Enable or disable lockfile concurrency protection preventing parallel collisions.',
      '      Example:',
      '        l --no-lock paper.tex',
      '',
      '  --no-env',
      '      Reset TeX environment variables (TEXINPUTS, BIBINPUTS, BSTINPUTS) to standard defaults.',
      '      Example:',
      '        l --no-env paper.tex',
      '',
      '  --emacs',
      '      Format warnings and errors for Emacs AUCTeX integration (suppressing line prefixes).',
      '      Example:',
      '        l --emacs paper.tex',
      '',
      '  -cc, --compile',
      '      Format diagnostics in strict GNU standard compiler format (file:line:col: severity: msg)',
      '      for editor/IDE integration (Vim :make, VS Code problem matchers, CI log matchers).',
      '      Example:',
      '        l -cc paper.tex',
      '        l --compile paper.tex',
      '',
      '  --config-init',
      '      Create a local .l.jsonc configuration template in the current directory and exit.',
      '      Example:',
      '        l --config-init',
      '',
      '  --config-show',
      '      Display active configuration sources (global and local) and resolved settings and exit.',
      '      Pass --global or --local to inspect a specific configuration file.',
      '      Example:',
      '        l --config-show',
      '        l --config-show --global',
      '        l --config-show --local',
      '',
      '  --config-save',
      '      Save specified CLI option choices directly into the configuration file',
      '      (default: local .l.jsonc, or global config with --global).',
      '      Example:',
      '        l -I --config-save',
      '        l -I --config-save --global',
      '        l -e lualatex --config-save',
      '',
      '  --global',
      '      Target global configuration (~/.config/leeni/config.jsonc) for config operations',
      '      such as --config-save or --config-show.',
      '      Example:',
      '        l -I --config-save --global',
      '        l --config-show --global',
      '',
      '  --local',
      '      Target local configuration (./.l.jsonc) for config operations such as',
      '      --config-save or --config-show (default behavior).',
      '      Example:',
      '        l -I --config-save --local',
      '        l --config-show --local',
      '',
      '  --vscode-init',
      '      Create VS Code tasks.json and settings.json in .vscode/ for LaTeX Workshop and exit.',
      '      Example:',
      '        l --vscode-init',
      '',
      '  --gitignore-init',
      '      Create or add standard LaTeX, SyncTeX, and junk/ rules to .gitignore and exit.',
      '      Additive: preserves existing rules and only appends missing entries.',
      '      Example:',
      '        l --gitignore-init'
    ].join("\n")
  end

  def self.general_options_section
    [
      'General Options:',
      '  -m, --main',
      '      Print the detected main LaTeX root document file and exit without compiling.',
      '      Example:',
      '        l -m',
      '',
      '  -M, --deps',
      '      Print Makefile dependency rule for the document and exit.',
      '      Example:',
      '        l -M paper.tex',
      '',
      '  -V, --version',
      '      Show version information and exit.',
      '      Example:',
      '        l -V',
      '',
      '  -E, --examples',
      '      Show detailed usage examples and common workflows.',
      '      Example:',
      '        l -E',
      '',
      '  -h, --help',
      '      Show condensed help summary of everyday options.',
      '      Example:',
      '        l -h',
      '',
      '  -H, --help-all',
      '      Show this comprehensive manual with detailed explanations and examples for all options.',
      '      Example:',
      '        l -H',
      '',
      '  --help-style STYLE',
      '      Help display style: plain (standard Unix style, default) or lines (subdued dividers).',
      '      Example:',
      '        l -H --help-style lines'
    ].join("\n")
  end
end
