title: Leeni
description: Fast, isolated, intelligent LaTeX compilation manager
theme: jekyll-theme-primer

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - internal/
  - demos/
  - data/
  - vim/
